### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [facebookresearch/ActivityNet-Entities#4]
Hello,
How long does your mode need to train with a single GPU?

**Comment by LuoweiZhou** [comment]
@AmingWu we apply multi-GPU training for all the experiments due to the large amount of data we have. We have released our code on GVD and you can follow the [Quick Start](https://github.com/facebookresearch/grounded-video-description#quick-start) to run single-GPU experiments (you might want to set the batch size to the maximum your GPU memory can fit).

**Comment by LuoweiZhou** [comment]
@AmingWu This might be a late reply but the single-GPU training from [here](https://github.com/facebookresearch/grounded-video-description#starter-code) takes about 30min per epoch (including language eval) and 20hr for 40 epochs on a TITAN Xp GPU.
